In [1]:
import pandas as pb

In [2]:
weather_data = pb.read_csv("C:\Data Analyst Training\Machine_learning_Project\Wather_Prediction\seattle-weather.csv")
weather_data.head()

         date  precipitation  temp_max  temp_min  wind  weather
0  01-01-2012            0.0      12.8       5.0   4.7  drizzle
1  01-02-2012           10.9      10.6       2.8   4.5     rain
2  01-03-2012            0.8      11.7       7.2   2.3     rain
3  01-04-2012           20.3      12.2       5.6   4.7     rain
4  01-05-2012            1.3       8.9       2.8   6.1     rain

In [3]:
weather_data.isnull().sum()

date             0
precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder

def add_label(df, column):
    df[column] = LabelEncoder().fit_transform(df[column])
    return df

weather_data = add_label(weather_data, "weather")
weather_data

            date  precipitation  temp_max  temp_min  wind  weather
0     01-01-2012            0.0      12.8       5.0   4.7        0
1     01-02-2012           10.9      10.6       2.8   4.5        2
2     01-03-2012            0.8      11.7       7.2   2.3        2
3     01-04-2012           20.3      12.2       5.6   4.7        2
4     01-05-2012            1.3       8.9       2.8   6.1        2
...          ...            ...       ...       ...   ...      ...
1456  12/27/2015            8.6       4.4       1.7   2.9        2
1457  12/28/2015            1.5       5.0       1.7   1.3        2
1458  12/29/2015            0.0       7.2       0.6   2.6        1
1459  12/30/2015            0.0       5.6      -1.0   3.4        4
1460  12/31/2015            0.0       5.6      -2.1   3.5        4

[1461 rows x 6 columns]

In [14]:
weather_column = ['precipitation' , 'temp_max', 'temp_min', 'wind']

In [19]:
def normalize_weather(weather_data, weather_column):
    weather_data[weather_column] = weather_data[weather_column] / weather_data[weather_column].max()
    return weather_data

weather_data = normalize_weather(weather_data, weather_column)
weather_data

            date  precipitation  temp_max  temp_min      wind  weather
0     01-01-2012       0.000000  0.359551  0.273224  0.494737        0
1     01-02-2012       0.194991  0.297753  0.153005  0.473684        2
2     01-03-2012       0.014311  0.328652  0.393443  0.242105        2
3     01-04-2012       0.363148  0.342697  0.306011  0.494737        2
4     01-05-2012       0.023256  0.250000  0.153005  0.642105        2
...          ...            ...       ...       ...       ...      ...
1456  12/27/2015       0.153846  0.123596  0.092896  0.305263        2
1457  12/28/2015       0.026834  0.140449  0.092896  0.136842        2
1458  12/29/2015       0.000000  0.202247  0.032787  0.273684        1
1459  12/30/2015       0.000000  0.157303 -0.054645  0.357895        4
1460  12/31/2015       0.000000  0.157303 -0.114754  0.368421        4

[1461 rows x 6 columns]

In [20]:
drop_date = weather_data.drop("date",axis=1)
drop_date

      precipitation  temp_max  temp_min      wind  weather
0          0.000000  0.359551  0.273224  0.494737        0
1          0.194991  0.297753  0.153005  0.473684        2
2          0.014311  0.328652  0.393443  0.242105        2
3          0.363148  0.342697  0.306011  0.494737        2
4          0.023256  0.250000  0.153005  0.642105        2
...             ...       ...       ...       ...      ...
1456       0.153846  0.123596  0.092896  0.305263        2
1457       0.026834  0.140449  0.092896  0.136842        2
1458       0.000000  0.202247  0.032787  0.273684        1
1459       0.000000  0.157303 -0.054645  0.357895        4
1460       0.000000  0.157303 -0.114754  0.368421        4

[1461 rows x 5 columns]

In [36]:
independent_x = weather_data.drop(["weather","date"],axis=1)
dependent_y = weather_data["weather"]

In [39]:
from sklearn.model_selection import train_test_split
independent_train, independent_test, dependent_train, dependent_test = train_test_split(independent_x, dependent_y, test_size = 0.2, random_state = 0)
print("x- Tarin",independent_train)
print("y- Tarin",dependent_train)

x- Tarin       precipitation  temp_max  temp_min      wind
646        0.123435  0.390449  0.426230  0.315789
92         0.000000  0.469101  0.240437  0.326316
818        0.250447  0.328652  0.393443  0.536842
302        0.194991  0.438202  0.546448  0.515789
1259       0.000000  0.671348  0.513661  0.273684
...             ...       ...       ...       ...
763        0.000000  0.250000  0.060109  0.263158
835        0.008945  0.404494  0.426230  0.421053
1216       0.000000  0.514045  0.486339  0.389474
559        0.000000  0.733146  0.606557  0.326316
684        0.053667  0.297753  0.393443  0.631579

[1168 rows x 4 columns]
y- Tarin 646     2
92      4
818     2
302     2
1259    4
       ..
763     4
835     2
1216    4
559     4
684     2
Name: weather, Length: 1168, dtype: int64

In [24]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\baps\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\baps\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
   -- ------------------------------------- 4.7/69.5 MB 37.4 MB/s eta 0:00:02
   ----------------- ---------------------- 29.9/69.5 MB 87.9 MB/s eta 0:00:01
   --------------------------------- ------ 57.4/69.5 MB 104.3 MB/s eta 0:00:01
   ---------------------------------------- 69.5/69.5 MB 90.9 MB/s  0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0
Note: you may need to restart the kernel to use updated packages.

In [25]:
from xgboost import XGBClassifier

In [42]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier()
model.fit(independent_train, dependent_train)
predictions = model.predict(independent_train)

predictions========= [2 4 2 ... 4 4 2]

In [43]:
model.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'log_loss',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [45]:
from sklearn.metrics import classification_report,accuracy_score

predictions = model.predict(independent_train)
print(accuracy_score(dependent_train,predictions))
print(classification_report(dependent_train,predictions))

0.9212328767123288
              precision    recall  f1-score   support

           0       1.00      0.35      0.52        43
           1       0.94      0.46      0.62        72
           2       1.00      0.95      0.98       518
           3       1.00      1.00      1.00        20
           4       0.85      1.00      0.92       515

    accuracy                           0.92      1168
   macro avg       0.96      0.75      0.81      1168
weighted avg       0.93      0.92      0.91      1168